environment: prod
log_config: env/prod/logging.yaml
collector:
  urls:
    national: https://www.rivm.nl/coronavirus-covid-19/actueel
    municipality: https://www.rivm.nl/coronavirus-covid-19/actueel
  municipalities: external/gemeenten.csv
  elements:
    national: table
    municipality: csvData
    metadata: mapTitles
store:
  path: data
