environment: development
log_config: env/dev/logging.yaml
collector:
  urls:
    national: https://data.rivm.nl/covid-19/COVID-19_aantallen_gemeente_cumulatief.csv
    municipality: https://www.rivm.nl/coronavirus-covid-19/actueel
    intensive_care:
      - https://www.stichting-nice.nl/covid-19/public/new-intake
      - https://www.stichting-nice.nl/covid-19/public/intake-count
      - https://www.stichting-nice.nl/covid-19/public/intake-cumulative
      - https://www.stichting-nice.nl/covid-19/public/ic-count
      - https://www.stichting-nice.nl/covid-19/public/died-and-survivors-cumulative
  municipalities: external/gemeenten.csv
  elements:
    national: null
    municipality: csvData
    date: content-date-edited
store:
  path: data
