environment: development
log_config: env/dev/logging.yaml
collector:
  url: https://www.rivm.nl/coronavirus-covid-19/actueel
  municipalities: external/gemeenten.csv
  elements:
    data: csvData
    metadata: mapTitles
    general: table
store:
  path: data
